"""Code-execution E2E replay: re-run the user's real pipeline with the LLM swapped
to a cheaper model, inside a throwaway git worktree, so tools fire and loops run.

This is the "watch out for cascading failures" path. It is deliberately conservative:
it sets up an isolated sandbox and a model-injection shim, then invokes a user-provided
run command. The heavy lifting (which model maps to what) is driven by a generated
`inject_sitecustomize.py` that patches common LLM client constructors at import time.

CLI:
    python run_pipeline.py --codebase ./repo \
        --run "python -m myagent --task-file {task}" \
        --task-input task.json \
        --swap-model openai/gpt-4o-mini \
        --out replay_result.json

Notes / safety:
  * Uses `git worktree add` on the codebase HEAD so writes don't touch the real tree.
  * Injects a sitecustomize that redirects OpenAI/Anthropic SDKs + LangChain chat
    models to OpenRouter and forces the swap model.
  * By default network egress is NOT firewalled — for untrusted code run inside Docker.
    Pass --docker to wrap the run in a container if available.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import tempfile
import uuid

from common import eprint

SITECUSTOMIZE = r"""
# Auto-generated by cheaper-models. Redirects LLM SDKs to OpenRouter and forces a model.
import os, functools
_SWAP = os.environ.get("CM_SWAP_MODEL")
_BASE = "https://openrouter.ai/api/v1"
_KEY = os.environ.get("OPENROUTER_API_KEY")

def _patch_openai():
    try:
        import openai
    except Exception:
        return
    for cls_name in ("OpenAI", "AsyncOpenAI"):
        cls = getattr(openai, cls_name, None)
        if not cls:
            continue
        orig = cls.__init__
        @functools.wraps(orig)
        def _init(self, *a, __orig=orig, **kw):
            kw["base_url"] = _BASE
            if _KEY:
                kw["api_key"] = _KEY
            return __orig(self, *a, **kw)
        cls.__init__ = _init

def _patch_langchain():
    try:
        import langchain_openai
        orig = langchain_openai.ChatOpenAI.__init__
        @functools.wraps(orig)
        def _init(self, *a, __orig=orig, **kw):
            if _SWAP: kw["model"] = _SWAP
            kw.setdefault("base_url", _BASE)
            if _KEY: kw.setdefault("api_key", _KEY)
            return __orig(self, *a, **kw)
        langchain_openai.ChatOpenAI.__init__ = _init
    except Exception:
        pass
    try:
        import langchain_anthropic  # routed through OpenRouter's OpenAI-compat won't match;
        # left as a hook — prefer a LiteLLM anthropic-passthrough proxy for anthropic clients.
    except Exception:
        pass

_patch_openai()
_patch_langchain()
"""


def sh(cmd: list[str], **kw) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, capture_output=True, text=True, **kw)


def make_worktree(codebase: str) -> tuple[str, str]:
    head = sh(["git", "-C", codebase, "rev-parse", "HEAD"])
    if head.returncode != 0:
        raise RuntimeError(f"{codebase} is not a git repo: {head.stderr.strip()}")
    wt = os.path.join(tempfile.gettempdir(), f"cm-replay-{uuid.uuid4().hex[:8]}")
    r = sh(["git", "-C", codebase, "worktree", "add", "--detach", wt, head.stdout.strip()])
    if r.returncode != 0:
        raise RuntimeError(f"worktree add failed: {r.stderr.strip()}")
    return wt, head.stdout.strip()


def remove_worktree(codebase: str, wt: str) -> None:
    sh(["git", "-C", codebase, "worktree", "remove", "--force", wt])
    shutil.rmtree(wt, ignore_errors=True)


def run(
    codebase: str,
    run_cmd: str,
    task_input: str | None,
    swap_model: str,
    use_docker: bool = False,
    timeout: int = 900,
) -> dict:
    wt, head = make_worktree(codebase)
    try:
        # drop the injection shim + point PYTHONPATH at it so sitecustomize loads first
        shim_dir = os.path.join(wt, ".cm_shim")
        os.makedirs(shim_dir, exist_ok=True)
        with open(os.path.join(shim_dir, "sitecustomize.py"), "w") as f:
            f.write(SITECUSTOMIZE)

        task_path = ""
        if task_input:
            task_path = os.path.join(wt, "cm_task_input.json")
            shutil.copyfile(task_input, task_path)

        cmd = run_cmd.replace("{task}", task_path)
        env = dict(os.environ)
        env["PYTHONPATH"] = shim_dir + os.pathsep + env.get("PYTHONPATH", "")
        env["CM_SWAP_MODEL"] = swap_model
        env["OPENAI_BASE_URL"] = "https://openrouter.ai/api/v1"
        if env.get("OPENROUTER_API_KEY"):
            env["OPENAI_API_KEY"] = env["OPENROUTER_API_KEY"]

        if use_docker and shutil.which("docker"):
            # minimal container wrap; assumes a python image with the repo mounted
            docker = [
                "docker",
                "run",
                "--rm",
                "-v",
                f"{wt}:/app",
                "-w",
                "/app",
                "-e",
                f"CM_SWAP_MODEL={swap_model}",
                "-e",
                "OPENAI_BASE_URL=https://openrouter.ai/api/v1",
                "-e",
                f"OPENAI_API_KEY={env.get('OPENAI_API_KEY', '')}",
                "-e",
                "PYTHONPATH=/app/.cm_shim",
                "python:3.12-slim",
                "bash",
                "-lc",
                cmd,
            ]
            proc = sh(docker, timeout=timeout)
        else:
            proc = subprocess.run(
                cmd, shell=True, cwd=wt, env=env, capture_output=True, text=True, timeout=timeout
            )

        return {
            "swap_model": swap_model,
            "head": head,
            "returncode": proc.returncode,
            "stdout": proc.stdout[-20000:],
            "stderr": proc.stderr[-8000:],
            "worktree": wt,
            "ok": proc.returncode == 0,
        }
    finally:
        remove_worktree(codebase, wt)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--codebase", required=True)
    ap.add_argument(
        "--run", required=True, help="run command; {task} is replaced with the task input path"
    )
    ap.add_argument("--task-input")
    ap.add_argument("--swap-model", required=True)
    ap.add_argument("--docker", action="store_true")
    ap.add_argument("--timeout", type=int, default=900)
    ap.add_argument("--out")
    args = ap.parse_args()

    result = run(
        args.codebase,
        args.run,
        args.task_input,
        args.swap_model,
        use_docker=args.docker,
        timeout=args.timeout,
    )
    eprint(
        f"E2E replay {'OK' if result['ok'] else 'FAILED'} (rc={result['returncode']}) model={args.swap_model}"
    )
    if args.out:
        from common import dump_json

        dump_json(result, args.out)
    else:
        print(json.dumps(result, indent=2, default=str))
    return 0 if result["ok"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
